from selenium import webdriver
print("SELENIUM IMPORTED")
import os
print("OS IMPORTED")
chrome_options = webdriver.ChromeOptions()
print("OPTIONS CREATED")
chrome_options.add_argument("--headless")
print("HEADLESS DONE")
chrome_options.add_argument("--disable-dev-shm-usage")
print("DISABLE DEV SHM USAGE DONE")
chrome_options.add_argument("--no-sandbox")
print("NO SANDBOX DONE")
chrome_options.binary_location = os.environ.get("GOOGLE_CHROME_BIN")
print("CHROME BINARY LOCATION SET")
driver = webdriver.Chrome(executable_path=os.environ.get("CHROMEDRIVER_PATH"), chrome_options=chrome_options)
print("DRIVER CREATED")
driver.get("https://medium.com")
print("WEBPAGE OPEN")
print(driver.page_source)
print("Finished!")
